--Base de Datos System LF

--CLIENTES

CREATE TABLE CLIENTES
(
ID INT IDENTITY(1,1) NOT NULL,
COD_CLIENTE AS ('CL-' + RIGHT ('00000' + CONVERT(NVARCHAR,ID),(5) )  ),
DNI NVARCHAR(50)  PRIMARY KEY NOT NULL,
NOMBRE_CL NVARCHAR(50) NOT NULL,
APELLIDO_CL NVARCHAR(50) NOT NULL,
GENERO NVARCHAR(1) NOT NULL,
TELEFONO_CL NVARCHAR(30),
DIRECCION_CL NVARCHAR(150) NOT NULL,
ESTADO_CL NVARCHAR(30) NOT NULL,
FECHA_REG DATETIME NOT NULL
)

--PRESTAMOS

CREATE TABLE PRESTAMOS
(
ID INT IDENTITY(1,1) NOT NULL,
COD_PR AS ('PRES-'+ RIGHT('00000' + CONVERT(NVARCHAR,ID),(5) ) )   ,
DNI NVARCHAR(50)  NOT NULL,
MONTO MONEY NOT NULL,
FECHA_INIC DATE NOT NULL,
FECHA_FIN DATE NOT NULL,
CUOTA MONEY NOT NULL
PRIMARY KEY(DNI)
)

--CUOTAS

CREATE TABLE CUOTAS
(
NUM_CUOTA INT NOT NULL,
DNI NVARCHAR(50) NOT NULL,
FECHA_PAGO DATE NOT NULL,
CAPITAL MONEY NOT NULL,
INTERES MONEY NOT NULL,
CUOTA MONEY NOT NULL
PRIMARY KEY(NUM_CUOTA,DNI)
)

--PAGOS

CREATE TABLE PAGOS
(
ID INT IDENTITY(1,1) PRIMARY KEY ,
COD_PAGO AS ('PAG-' + RIGHT('00000' + CONVERT(NVARCHAR,ID),(5) ) ),
TRANS_PAGO DATETIME NOT NULL,
SALDO_PEN MONEY NOT NULL,
SALDO_ACTUAL MONEY NOT NULL,
NUM_CUOTA INT NOT NULL,
DNI NVARCHAR(50) NOT NULL,

FOREIGN KEY(NUM_CUOTA,DNI) REFERENCES CUOTAS(NUM_CUOTA,DNI)
)

