alter PROCEDURE G_CLIENTE
(
@DNI NVARCHAR(50)   ,
@NOMBRE_CL NVARCHAR(50) ,
@APELLIDO_CL NVARCHAR(50) ,
@GENERO NVARCHAR(1) ,
@TELEFONO_CL NVARCHAR(30),
@DIRECCION_CL NVARCHAR(150) ,
@ESTADO_CL NVARCHAR(30),
@MSJ NVARCHAR(150) OUTPUT

)
AS BEGIN

if(exists(select * from CLIENTES WHERE DNI = @DNI))
SET @MSJ = 'EL Cliente ' + @DNI + ' ya esta Registrado'

else BEGIN

insert into CLIENTES  
(DNI,NOMBRE_CL,APELLIDO_CL,GENERO,TELEFONO_CL,DIRECCION_CL,ESTADO_CL,FECHA_REG)
VALUES
(@DNI,@NOMBRE_CL,@APELLIDO_CL,@GENERO,@TELEFONO_CL,@DIRECCION_CL,@ESTADO_CL,GETDATE())

SET @MSJ = 'EL Cliente ' + CONCAT(@NOMBRE_CL,',',@APELLIDO_CL) + ' se registro con exito' 

end
END
