


CREATE PROCEDURE G_PAGOS
(
@DNI NVARCHAR(30),
@NUM_CUOTA INT,
@PAGO MONEY,
@SALDO_PENDIENTE MONEY,
@AVISO NVARCHAR(150) OUTPUT
)
AS BEGIN

DECLARE @PLAZO NVARCHAR(2) = (SELECT SUBSTRING(PLAZO,1,2)[Cadena] FROM PRESTAMOS where DNI = @DNI)
DECLARE @SALDO_ANTERIOR MONEY = (SELECT [Saldo Anterior] FROM [dbo].[FN_PAGOS](@DNI) WHERE NUM_CUOTA = @NUM_CUOTA)
DECLARE @SALDO_ACTUAL MONEY = (SELECT [Saldo actual] FROM [dbo].[FN_PAGOS](@DNI) WHERE NUM_CUOTA = @NUM_CUOTA)

IF(NOT EXISTS(SELECT * FROM PAGOS WHERE DNI = @DNI))
BEGIN

insert into PAGOS (DNI,SALDO_ACTUAL,SALDO_ANT,CUOTAS_PAGADAS)
values
(
@DNI,
@SALDO_ACTUAL,
@SALDO_ANTERIOR,
@NUM_CUOTA
)

insert into DETALLE_PAGO
(COD_PAGO,NUM_CUOTA,TOTAL_PAGO,SALDO_PENDIENTE,FECHA_TRANSACCION)
VALUES
(
(SELECT ID FROM PAGOS WHERE DNI = @DNI),
@NUM_CUOTA,
@PAGO,
@SALDO_PENDIENTE,
GETDATE()
)
END -- IF SI NO EXISTE EN PAGOS
else BEGIN

IF(@PLAZO IN ('12','15','18','24','QU','SE'))
BEGIN

IF( (@NUM_CUOTA = 12  AND @PLAZO = '12') OR (@NUM_CUOTA = 15 AND @PLAZO = '15')
OR ( @NUM_CUOTA = 18 AND @PLAZO = '18') OR (@NUM_CUOTA = 24 AND @PLAZO = '24')
OR (@NUM_CUOTA = 4 OR @PLAZO = 'SE') OR (@NUM_CUOTA = 2 AND @PLAZO = 'QU' ))
BEGIN

--ACTUALIZAR PAGO
UPDATE PAGOS SET SALDO_ANT = @SALDO_ANTERIOR , SALDO_ACTUAL = @SALDO_ACTUAL,
CUOTAS_PAGADAS = @NUM_CUOTA,COD_ESTADO = 2 WHERE DNI = @DNI

--DETALLE PAGO
insert into DETALLE_PAGO
(COD_PAGO,NUM_CUOTA,TOTAL_PAGO,SALDO_PENDIENTE,FECHA_TRANSACCION)
VALUES
(
(SELECT ID FROM PAGOS WHERE DNI = @DNI),
@NUM_CUOTA,
@PAGO,
@SALDO_PENDIENTE,
GETDATE()
)


END --ULTIMA CUOTA
ELSE BEGIN

--ACTUALIZAR PAGO
UPDATE PAGOS SET SALDO_ANT = @SALDO_ANTERIOR , SALDO_ACTUAL = @SALDO_ACTUAL,
CUOTAS_PAGADAS = @NUM_CUOTA WHERE DNI = @DNI

--DETALLE PAGO
insert into DETALLE_PAGO
(COD_PAGO,NUM_CUOTA,TOTAL_PAGO,SALDO_PENDIENTE,FECHA_TRANSACCION)
VALUES
(
(SELECT ID FROM PAGOS WHERE DNI = @DNI),
@NUM_CUOTA,
@PAGO,
@SALDO_PENDIENTE,
GETDATE()
)


END --SI NO ES ULTIMA CUOTA

END --END IF BEGIN PLAZO

END -- ELSE BEGIN 



END -- END AS BEGIN


