ALTER PROCEDURE G_PRESTAMO
(
@DNI NVARCHAR(50) ,
@MONTO MONEY ,
@FECHA_INIC nvarchar(50) ,
@FECHA_FIN nvarchar(50),
@CUOTA MONEY ,
@INT_T MONEY,
@CAP_T MONEY,
@MSJ NVARCHAR(150) OUTPUT
)
AS BEGIN
IF(EXISTS (SELECT * FROM CLIENTES WHERE DNI = @DNI) AND NOT EXISTS (SELECT * FROM PRESTAMOS WHERE DNI = @DNI))
BEGIN

INSERT INTO PRESTAMOS
(DNI,MONTO,FECHA_INIC,FECHA_FIN,CUOTA,INTERES_TOT,CAPITAL_TOT)
VALUES
(@DNI,ROUND( @MONTO,2),@FECHA_INIC,@FECHA_FIN,ROUND(@CUOTA,2),ROUND(@INT_T,2),ROUND(@CAP_T,2))
SET @MSJ = 'EL PRESTAMO RESULTO EXITOSO'

END
ELSE BEGIN


SET @MSJ = 'NO SE PUDO ACREDITAR EL PRESTAMO,DEBE REGISTRARSE'

END
END
